name: subscription_reminder
description: "Subscription Reminder Flutter Application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.1.5

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Device feature (GPS)
  geolocator: ^14.0.2

  # Notifications
  flutter_local_notifications: ^19.4.2

  # Date formatting
  intl: ^0.20.2
  firebase_core: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true