// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBUS12Cb6gt5-8Mc9j53i09ty3ROoS5E8',
    appId: '1:527632286732:web:e5945805fb202df7e2da29',
    messagingSenderId: '527632286732',
    projectId: 'subscription-reminder-24780',
    authDomain: 'subscription-reminder-24780.firebaseapp.com',
    storageBucket: 'subscription-reminder-24780.firebasestorage.app',
    measurementId: 'G-88TTXFXZW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByyh6IvApE-D75Ry3UbMoL4G5Rt6qkwho',
    appId: '1:527632286732:android:48c04baf070d4c91e2da29',
    messagingSenderId: '527632286732',
    projectId: 'subscription-reminder-24780',
    storageBucket: 'subscription-reminder-24780.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdGIrrf4UIK9vkJBSe2xvjv7eGXzlc-5I',
    appId: '1:527632286732:ios:69a7f30a52e76ed7e2da29',
    messagingSenderId: '527632286732',
    projectId: 'subscription-reminder-24780',
    storageBucket: 'subscription-reminder-24780.firebasestorage.app',
    iosBundleId: 'com.example.subscriptionReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdGIrrf4UIK9vkJBSe2xvjv7eGXzlc-5I',
    appId: '1:527632286732:ios:69a7f30a52e76ed7e2da29',
    messagingSenderId: '527632286732',
    projectId: 'subscription-reminder-24780',
    storageBucket: 'subscription-reminder-24780.firebasestorage.app',
    iosBundleId: 'com.example.subscriptionReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBUS12Cb6gt5-8Mc9j53i09ty3ROoS5E8',
    appId: '1:527632286732:web:f34e1e3d644b4a87e2da29',
    messagingSenderId: '527632286732',
    projectId: 'subscription-reminder-24780',
    authDomain: 'subscription-reminder-24780.firebaseapp.com',
    storageBucket: 'subscription-reminder-24780.firebasestorage.app',
    measurementId: 'G-LB969HJJMH',
  );

}